[package]
name = "vsched"
version.workspace = true
edition.workspace = true
authors = ["Fangliang Zhao <1491657576@qq.com>"]
description = "Shared Scheduler via vDSO"
license.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = ["multitask"]

irq = []
tls = []
preempt = ["irq"]
smp = []

multitask = []
sched-fifo = ["multitask"]
sched-rr = ["multitask", "preempt"]
sched-cfs = ["multitask", "preempt"]

[dependencies]
cfg-if = "1.0"
hal = { workspace = true }
scheduler = { workspace = true }
config = { workspace = true }
cpumask = "0.1"
memory_addr = "0.4"
crossbeam = { version = "0.8", default-features = false }
